name: Build LaTeX documents
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile Resume
        uses: xu-cheng/latex-action@master
        with:
          working_directory: "./"
          root_file: "resume.tex"
      - name: Set enviroment for github-release
        run: |
          dt=$(date '+%Y.%m.%d-%H.%M.%S')
          echo $dt
          echo ::set-env name=RELEASE_TAG::$dt
      - name: Create Release
        uses: meeDamian/github-release@1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          gzip: false
          files: >
            resume.pdf
